version: 2

updates: []
#  - package-ecosystem: "bundler"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      day: "friday"
#    allow:
#      - dependency-type: "all"
#  - package-ecosystem: "npm"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      day: "friday"
#    allow:
#      - dependency-type: "all"
