version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 0
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
