name: "Setup test environment"
inputs:
  ruby:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Find yarn cache location
      id: yarn-cache
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
    - name: JS package cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages
      run: |
        bin/yarn install --pure-lockfile
      shell: bash
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
    - name: Set up database schema
      run: bin/rails db:schema:load
      shell: bash
