require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  # rubocop-rails_config still supports Ruby 2.4
  TargetRubyVersion: 3.1
  DisabledByDefault: false
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    # Additional exclude files by rubocop-rails_config
    - 'bin/**/*'
    #  - 'config/**/*'
    - 'db/**/*'
    - "lib/flickraw-cached.rb"
    - 'lib/tasks/taxonomy/**/*'
    - 'lib/tasks/one-off/**/*'
    - config.ru
    - contest*.rb

Performance:
  Exclude:
    - '**/test/**/*'

Performance/FlatMap:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

# FIXME: revisit and fix!
Style/MethodCallWithArgsParentheses:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/DotPosition:
  Enabled: false
# end: revisit and fix!

# - My modification -
Style/PreferredHashMethods:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters :
  Enabled: false

Style/WordArray:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/Send:
  Enabled: true

Style/GlobalVars:
  Exclude:
    - test/**/*.rb

Style/ClassAndModuleChildren:
  Exclude:
    - '**/test/**/*'
    - 'lib/core_ext/**/*.rb'

# FIXME: look into enabling
Style/ClassVars:
  Enabled: false

# FIXME: look into enabling
Style/MissingRespondToMissing:
  Enabled: false

# Improved readability, but look into refactoring
Style/IfInsideElse:
  Enabled: false

# Improved readability
Style/NegatedIf:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/SpaceInsideBlockBraces:
  Enabled: false
  EnforcedStyleForEmptyBraces: space

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

# Readability
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/ErbNewArguments:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

# Readability, but maybe leave only in tests
Lint/UselessAssignment:
  Enabled: false
#  Exclude:
#    - test/**/*.rb

