require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  # rubocop-rails_config still supports Ruby 2.4
  TargetRubyVersion: 3.0
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    # Additional exclude files by rubocop-rails_config
    - 'bin/**/*'
    #  - 'config/**/*'
    - 'db/**/*'
    - "lib/flickraw-cached.rb"
    - 'lib/tasks/taxonomy/**/*'
    - config.ru

Performance:
  Exclude:
    - '**/test/**/*'

Performance/FlatMap:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

# FIXME: temporary!
Style/MethodCallWithArgsParentheses:
  Enabled: false
Layout/LineLength:
  Enabled: false

# - My modification -

Style/WordArray:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/Send:
  Enabled: true

Layout/ClosingHeredocIndentation:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Layout/SpaceInsideBlockBraces:
  Enabled: false
  EnforcedStyleForEmptyBraces: space

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Lint/ErbNewArguments:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true
