services:
  web:
    container_name: quails_web
    build:
      context: .
    image: quails-app
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@database/quails_docker
      RAILS_SERVE_STATIC_FILES: "true"
      REDIS_CACHE_URL: redis://cache
      REDIS_RESQUE_URL: redis://resque-redis
    # Another approach - copy .env.production and rely on dotenv
    env_file:
      # In the env file do not use quotes (neither single nor double)!!!
      - .env.docker
    command: bundle exec puma -C config/puma.rb
    ports:
      - "5000:3000"
    depends_on:
      - database
      - cache
      - resque-redis
      - resque
    volumes:
      - rails_app_tmp:/app/tmp
      - rails_app_storage:/app/storage

  resque:
    container_name: quails_resque
    image: quails-app
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@database/quails_docker
      RAILS_SERVE_STATIC_FILES: "true"
      REDIS_CACHE_URL: redis://cache
      REDIS_RESQUE_URL: redis://resque-redis
      COUNT: 1
      INTERVAL: 5
      QUEUE: quails_production_default,quails_production_*
    # Another approach - copy .env.production nad rely on dotenv
    env_file:
      # In the env file do not use quotes (neither single nor double)!!!
      - .env.docker
    command: bin/rake resque:workers
    depends_on:
      - database
      - cache
      - resque-redis
    volumes:
      - rails_app_pids:/app/tmp/pids
      - rails_app_tmp:/app/tmp
      - rails_app_storage:/app/storage

  database:
    container_name: quails_database
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Temporarily to seed database
    #    ports:
    #      - "5499:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    container_name: quails_cache
    image: redis:5-alpine
    # This is cache
    command: redis-server --maxmemory 25mb --maxmemory-policy allkeys-lru --save 120 1
    # It is beneficial to preserve cache between deploys, but it can be cleared
    volumes:
      - cache_data:/data

  resque-redis:
    container_name: quails_resque_redis
    image: redis:5-alpine
    command: redis-server --save 120 1
    # Preserve resque data
    volumes:
      - resque_jobs_data:/data

# Declare the volumes that our application uses.
volumes:
  db_data:
  cache_data:
  resque_jobs_data:
  rails_app_storage:
  rails_app_pids:
  rails_app_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
