# frozen_string_literal: true

require "test_helper"

class PostCoreTest < ActiveSupport::TestCase
  test "slug is required" do
    core = build(:post_core, slug: "")
    assert_not_predicate core, :valid?
  end

  test "slug cannot contain space" do
    core = build(:post_core, slug: "kyiv observations")
    assert_not_predicate core, :valid?
  end

  test "shout cores auto-generate a slug from today when no post exists yet" do
    today = Time.current.strftime("%Y%m%d")
    core = create(:post_core, slug: "", shout: true)
    assert_match(/\Ashout-#{today}-[0-9a-f]+\z/, core.slug)
  end

  test "shout cores reuse the first post's face_date when regenerating the slug" do
    core = create(:post_core, shout: true)
    create(:post, post_core: core, face_date: "2015-08-20 10:00:00")
    core.update!(slug: "")
    assert_match(/\Ashout-20150820-[0-9a-f]+\z/, core.slug)
  end

  test "autogenerated shout slugs do not clash" do
    core1 = create(:post_core, slug: "", shout: true)
    core2 = create(:post_core, slug: "", shout: true)
    assert_not_equal core1.slug, core2.slug
  end
end
