# use SHA1 encoded password for production
production:
  admin:
    username: <%= ENV['admin_username'] %>
    password: <%= ENV['admin_password'] %>
    cookie_value: <%= ENV['admin_cookie_value'] %>
  secret_token: <%= ENV['quails_secret_token'] %>
  image_host: <%= ENV['quails_image_host'] %>

## use plain or SHA1 encoded password for development
#development:
#  admin:
#    free_access: true # works only in dev mode
#    cookie_value: admin
#  image_host:
#  secret_token: <%= SecureRandom.hex(30) %>
#
## use plain text password for test environment
#test:
#  admin:
#    username: testuser
#    password: testpasswd
#    cookie_value: test cookie
#  secret_token: <%= SecureRandom.hex(30) %>
#  image_host:
