# use plain or SHA1 encoded password for development and production
development:
  free_access: true # works only in dev mode
  admin_session_ask: dontask
  admin_session_reply: dontell
  images_host:
  secret_token: <%= SecureRandom.hex(30) %>
  flickr:
    api_key:
    shared_secret:
    auth_token:

# use plain text password for test environment
test:
  username: testuser
  password: testpasswd 
  admin_session_ask: testask
  admin_session_reply: testreply
  secret_token: <%= SecureRandom.hex(30) %>
  images_host:
  flickr:
    api_key:
    shared_secret:
    auth_token: