# use plain or SHA1 encoded password for development and production
development:
  admin:
    free_access: true # works only in dev mode
  images_host:
  secret_token: <%= SecureRandom.hex(30) %>
  flickr:
    api_key:
    shared_secret:
    auth_token:

# use plain text password for test environment
test:
  admin:
    username: testuser
    password: testpasswd
  secret_token: <%= SecureRandom.hex(30) %>
  images_host:
  flickr:
    api_key:
    shared_secret:
    auth_token: