# use SHA1 encoded password for development and production
production:
  admin:
    username: <%= ENV['username'] %>
    password: <%= ENV['password'] %>
  secret_token: <%= ENV['secret_token'] %>
  images_host: <%= ENV['images_host'] %>
  flickr:
    api_key: <%= ENV['flickr_api_key'] %>
    shared_secret: <%= ENV['flickr_secret'] %>
    auth_token: <%= ENV['flickr_token'] %>