# use SHA1 encoded password for production
production:
  admin:
    username: admin
    password: admin
    cookie_value: <%= SecureRandom.hex(16) %>
  secret_token: <%= SecureRandom.hex(30) %>
  image_host:

# use plain or SHA1 encoded password for development
development:
  admin:
    free_access: true # works only in dev mode
    cookie_value: admin
  secret_token: <%= SecureRandom.hex(30) %>
  image_host:

# use plain text password for test environment
test:
  admin:
    username: test
    password: test
    cookie_value: test
  secret_token: <%= SecureRandom.hex(30) %>
  image_host:
