# use SHA1 encoded password for production
production:
  admin:
    username: admin
    password: admin
    cookie_value: <%= SecureRandom.hex(16) %>
  secret_token: <%= SecureRandom.hex(30) %>
  image_host: /photos
#  local_image_path:
#  google_cse:
#  ga_code:

# use plain or SHA1 encoded password for development
development:
  admin:
    cookie_value: admin
  secret_token: <%= SecureRandom.hex(30) %>
  image_host: /photos
#  google_cse:

# use plain text password for test environment
test:
  admin:
    username: test
    password: test
    cookie_value: test
  secret_token: <%= SecureRandom.hex(30) %>
  # WORKAROUND for Capybara not being able to find dummy thumbnails: this should not be your app!
  image_host: http://localhost/photos
