# use SHA1 encoded password for development and production
production:
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>
  admin_session_ask: <%= ENV['admin_session_ask'] %>
  admin_session_reply: <%= ENV['admin_session_reply'] %>
  images_host: <%= ENV['images_host'] %>
  flickr:
    api_key: <%= ENV['flickr_api_key'] %>
    shared_secret: <%= ENV['flickr_secret'] %>
    auth_token: <%= ENV['flickr_token'] %>

development:
  free_access: true # works only in dev mode
  admin_session_ask: dontask
  admin_session_reply: dontell
  images_host:
  flickr:
    api_key:
    shared_secret:
    auth_token:

# use plain text password for test environment
test:
  username: testuser
  password_plain: testpasswd
  admin_session_ask: testask
  admin_session_reply: testreply
  images_host:
  flickr:
    api_key:
    shared_secret:
    auth_token: