# use SHA1 encoded password for development and production
production:
  username:
  password:

development:
  username:
  password:

# use plain text password for test environment
test:
  username: testuser
  password: testpasswd