# use SHA1 encoded password for production
production:
  admin:
    username: <%= ENV['username'] %>
    password: <%= ENV['password'] %>
    cookie_value: <%= ENV['cookie_value'] %>
  secret_token: <%= ENV['secret_token'] %>
  images_host: <%= ENV['images_host'] %>

## use plain or SHA1 encoded password for development
#development:
#  admin:
#    free_access: true # works only in dev mode
#    cookie_value: admin
#  images_host:
#  secret_token: <%= SecureRandom.hex(30) %>
#
## use plain text password for test environment
#test:
#  admin:
#    username: testuser
#    password: testpasswd
#    cookie_value: test cookie
#  secret_token: <%= SecureRandom.hex(30) %>
#  images_host:
