# use SHA1 encoded password for development and production
development:
  free_access: true # works only in dev mode
  admin_session_ask: dontask
  admin_session_reply: dontell
  images_host:
  flickr:
    api_key:
    shared_secret:
    auth_token:

# use plain text password for test environment
test:
  username: testuser
  password_plain: testpasswd
  admin_session_ask: testask
  admin_session_reply: testreply
  images_host:
  flickr:
    api_key:
    shared_secret:
    auth_token: