test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

<% if Quails.env.live? || ENV["ACCESS_PROD_S3"] || ENV["PROD_S3"] %>
amazon:
  service: S3
  public: true
  region: <%= ENV["S3_BUCKET_REGION"] || ENV["AWS_REGION"] %>
  bucket: <%= ENV["S3_PROD_BUCKET"] %>
  upload:
    cache_control: "public, max-age=2592000"
    acl: public-read
<% end %>

<% if ENV["DEV_S3"] %>
amazon_dev:
  service: S3
  public: true
  region: <%= ENV["S3_BUCKET_REGION"] || ENV["AWS_REGION"] %>
  bucket: <%= ENV["S3_DEV_BUCKET"] %>
  upload:
    cache_control: "public, max-age=2592000"
    acl: public-read
<% end %>
# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
