class AddCardsTable < ActiveRecord::Migration
  def change

    create_table "cards", force: true do |t|
      t.date "observ_date", null: false
      t.integer "locus_id", null: false

      t.string  "biotope"
      t.string  "weather"
      t.string  "time"
      t.string  "route"

      t.text "notes"

      t.string  "observers"
      t.boolean "with_me", null: false, default: 't'

      t.integer "post_id"

      t.boolean "autogenerated", null: false, default: 'f'

      t.timestamps
    end

    add_column :observations, :card_id, :integer

  end
end
