class AutoGenerateCardsFromObservations < ActiveRecord::Migration
  def up
    Observation.scoped.group_by { |o| [o.observ_date, o.locus_id] }.each do |dateloc, observs|
      Card.create(autogenerated: true, observ_date: dateloc[0], locus_id: dateloc[1]) do |card|
        card.observations = observs
        card.with_me = observs.any?(&:mine)
        post_ids = observs.map(&:post_id).compact.uniq
        if post_ids.size == 1
          card.post_id = post_ids.first
        end
      end
    end

  end

  def down
  end
end
