import PropTypes from 'prop-types';
import React from 'react';
import DateOnCard from './DateOnCard';

const Card = ({
                card: {
                  id, observ_date, locus_id, biotope, weather, start_time, notes, observers, post_id, autogenerated,
                  kml_url, effort_type, duration_minutes, distance_kms, area_acres, resolved, ebird_id,
                  observations, locus, post
                }, saveCard
              }) => (
    <dl>
      <DateOnCard observ_date={observ_date}/>
    </dl>
);

Card.propTypes = {
  card: PropTypes.object.isRequired,
  saveCard: PropTypes.func.isRequired,
};

export default Card;
