name: Build and push Docker images
on:
  - workflow_dispatch
  - push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            public.ecr.aws/m7x1i1o0/quails-app
          tags: |
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.DOCKER_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DOCKER_AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=registry,ref=m7x1i1o0/quails-app:buildcache
          cache-to: type=registry,ref=m7x1i1o0/quails-app:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
