name: "Build image"
on:
  workflow_call:
    secrets:
      DOCKER_AWS_ACCESS_KEY_ID:
        required: true
      DOCKER_AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
jobs:
  build_and_push:
    name: "Build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            public.ecr.aws/m7x1i1o0/quails-app
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value={{branch}}-latest,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            type=sha,prefix={{branch}}-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.DOCKER_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DOCKER_AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # Path context is required for .dockerignore to work.
          context: .
          build-args: |
            GIT_REVISION=${{ github.sha }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
