name: "Build image"
on:
  workflow_call:
    inputs:
      platforms:
        type: string
    secrets:
      DOCKER_AWS_ACCESS_KEY_ID:
        required: true
      DOCKER_AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
    inputs:
      platforms: 
        default: linux/amd64,linux/arm64
        required: true
        description: "Platforms to build for"
        type: choice
        options:
        - linux/amd64,linux/arm64
        - linux/amd64
      debug:
        default: false
        required: false
        description: "Install convenience packages (psql etc)"
        type: boolean

jobs:
  build_and_push:
    name: "Build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/khustochka/quails
          tags: |
            type=raw,value=latest,suffix=${{inputs.debug && '-debug' || ''}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # type=raw,value={{branch}}-latest,suffix=${{inputs.debug && '-debug' || ''}},enable=${{ github.ref != format('refs/heads/{0}', 'main') && startsWith(github.ref, 'refs/heads/') }}
            type=raw,priority=1000,value={{tag}},suffix=${{inputs.debug && '-debug' || ''}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=sha,priority=800,prefix={{branch}}-,suffix=${{inputs.debug && '-debug' || ''}},enable=${{ startsWith(github.ref, 'refs/heads/') }}
            # type=sha,prefix={{tag}}-,suffix=${{inputs.debug && '-debug' || ''}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          AWS_REGION: us-east-1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          # Path context is required for .dockerignore to work.
          context: .
          platforms: ${{ inputs.platforms }}
          build-args: |
            GIT_REVISION=${{ github.sha }}
            GIT_REPOSITORY_URL=${{ format('{0}/{1}', github.server_url, github.repository) }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/khustochka/quails
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
