name: "CI Pipeline"
on:
  - push
jobs:
  tests:
    name: "Tests"
    uses: ./.github/workflows/tests.yml
    
  rubocop:
    name: "Rubocop"
    uses: ./.github/workflows/rubocop.yml

  build_image:
    name: "Docker image"
    uses: ./.github/workflows/build.yml
    with: 
      debug: false
    secrets:
      DOCKER_AWS_ACCESS_KEY_ID: ${{ secrets.DOCKER_AWS_ACCESS_KEY_ID }}
      DOCKER_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCKER_AWS_SECRET_ACCESS_KEY }}  
    needs:
      - tests
      - rubocop
    if: github.ref == 'refs/heads/main'

  deploy:
    name: "Deploy"
    uses: ./.github/workflows/deploy.yml
    with: 
      image_tag: ${{ needs.build_image.outputs.image_tag }}
      deploy_env: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    secrets:
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
      DEPLOY_SCRIPTS_REPO: ${{ secrets.DEPLOY_SCRIPTS_REPO }}
    needs:
      - build_image


#  lint:
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Install Ruby and gems
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true
#      # Add or replace any other lints here
#      - name: Security audit dependencies
#        run: bin/bundler-audit --update
#      - name: Security audit application code
#        run: bin/brakeman -q -w2
#      - name: Lint Ruby files
#        run: bin/rubocop --parallel
