name: Deploy
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
    secrets:
      DEPLOY_SSH_KEY:
        required: true
      DEPLOY_SSH_HOST:
        required: true
      DEPLOY_TARGET_DIR:
        required: true

  workflow_dispatch:
    inputs:
      image_tag:
        type: string
        required: true
        description: "Image tag"
      deploy_env:
        required: true
        description: "Deployment environment"
        type: choice
        options:
        - staging
        - production
        default: staging

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    concurrency: ${{ inputs.deploy_env }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host deploy_target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        shell: bash
        env:
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_USER: ${{ vars.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Check out the source
        run: ssh deploy_target 'export DEPLOY_DB_NAME=github-deploys.db && export DOCKER_IMAGE=${{ inputs.image_tag }} && cd ${{ secrets.DEPLOY_TARGET_DIR }} && git fetch && git reset --hard origin/main && ./deploy production'
        shell: bash
