# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Quails Tests & Build"
on:
  - push
jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: quails
          POSTGRES_DB: quails_test
          POSTGRES_PASSWORD: "quails"
    env:
      BUNDLE_WITHOUT: development
      RAILS_ENV: test
      DATABASE_URL: "postgres://quails:quails@localhost:5432/quails_test"
      MINITEST_REPORTER: Minitest::Reporters::SpecReporter
      COVERAGE: 1
      PARALLEL_WORKERS: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake
      - name: Code coverage results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Coverage
          path: coverage/

  system_test:
    name: ${{ matrix.name }} system tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Chrome
            js_driver: selenium
            js_browser: headless_chrome
            bundle_without: "development"
          - name: Firefox
            js_driver: selenium
            js_browser: headless_firefox
            bundle_without: "development"
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: quails
          POSTGRES_DB: quails_test
          POSTGRES_PASSWORD: "quails"
    env:
      BUNDLE_WITHOUT: ${{ matrix.bundle_without }}
      RAILS_ENV: test
      DATABASE_URL: "postgres://quails:quails@localhost:5432/quails_test"
      MINITEST_REPORTER: Minitest::Reporters::SpecReporter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        env:
          # To prevent ugly xvfb warning
          XDG_RUNTIME_DIR: '/tmp/runtime-runner'
          JS_DRIVER: ${{ matrix.js_driver }}
          JS_BROWSER: ${{ matrix.js_browser }}
        run: xvfb-run bin/rake test:system
      - name: Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Screenshots-${{ matrix.js_driver }}-${{ matrix.js_browser }}
          path: tmp/screenshots
  # Only build if the tests has passed.
  docker_build:
    name: Build and push image
    runs-on: ubuntu-latest
    needs:
      - test
      - system_test
    if: github.ref == 'refs/heads/kubernize'
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            public.ecr.aws/m7x1i1o0/quails-app
          tags: |
            type=raw,value=latest
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.DOCKER_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DOCKER_AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # Path context is required for .dockerignore to work.
          context: .
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
